context:
  name: samseg
  version: 0.6a0.dev0
  build: 0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  git: https://github.com/vcubiomag/samseg.git
  rev: "d11d9fafcc2def6f387443d7ba8e80a44a4425f6"

build:
  number: ${{ build|int + (microarch_level|int) * 100 }}
  script:
    - ${{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - if: microarch_level|int > 0
      then: x86_64-microarch-level ==${{ microarch_level }}
    - ${{ compiler('cxx') }}
    - cmake
  host:
    - python
    - pip
    - scikit-build-core
    - numpy >=2.0.0
    - pybind11
    - libitk-devel >=5.4.5
    - zlib
  run:
    - python
    - surfa >=0.6.4
    - scikit-learn
    - numpy
    - numba
    - libitk >=5.4.5
    - libzlib

tests:
  - python:
      imports:
        - samseg
  # Tensorflow not availble on Python@3.14
  # - script:
  #     - pytest -v tests
  #   files:
  #     source:
  #       - tests/
  #   requirements:
  #     run:
  #       - pytest
  #       - tensorflow

about:
  homepage: https://surfer.nmr.mgh.harvard.edu/fswiki/Samseg
  license: MIT
  summary: Sequence Adaptive Multimodal SEGmentation (SAMSEG)
  repository: https://github.com/freesurfer/samseg
  documentation: https://surfer.nmr.mgh.harvard.edu/fswiki/Samseg
