schema_version: 1

context:
  name: petsc
  version: "3.24.5"
  build: 0
  mpi: ${{ mpi | default('mpich') }}
  scalar: ${{ scalar | default('real') }}
  build_prefix: mkl_${{ scalar }}

recipe:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://web.cels.anl.gov/projects/petsc/download/release-snapshots/petsc-${{ version }}.tar.gz

outputs:
  - staging:
      name: petsc-build
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - if: win
          then: ifx_win-64
          else: ${{ compiler('fortran') }}
        - make
        - cmake
        - pkg-config
        - python 3.12.*
        - if: unix
          then:
            - bison
            - diffutils
            - gnuconfig
        - if: mpi == 'openmpi' and build_platform != target_platform
          then: ${{ mpi }}
      host:
        - ${{ mpi }}
        - mkl-devel
        - yaml
        - if: scalar == 'real'
          then:
            - hypre
        - libhwloc
        - metis
        - libptscotch
        - libscotch
        - libscotch * int32_*
        - libamd
        - libcholmod
        - libklu
        - libspqr
        - libumfpack
        - if: unix
          then:
            - parmetis
            - scalapack
            - mumps-mpi
            - hdf5
            - hdf5 * mpi_${{ mpi }}_*
            - fftw
            - fftw * mpi_${{ mpi }}_*
            - superlu
            - superlu_dist
    build:
      script:
        file: build_petsc
        env:
          scalar: ${{ scalar }}
          mpi: ${{ mpi }}

  - package:
      name: petsc
    inherit: petsc-build
    build:
      number: ${{ build }}
      string: ${{ build_prefix }}_h${{ hash }}_${{ build }}
      skip: osx or win
      variant:
        down_prioritize_variant: ${{ 1 if scalar == "complex" else 0 }}
      files:
        exclude:
          - share/petsc/examples/
          - share/petsc/datafiles/
          - lib/pkgconfig/PETSc.pc
    requirements:
      run:
        - mkl
      run_exports:
        weak:
          - ${{ pin_subpackage('petsc', upper_bound='x.x') }}
          - petsc * ${{ build_prefix }}_*

  - package:
      name: petsc4py
    inherit: petsc-build
    build:
      number: ${{ build }}
      skip: osx or win
      script:
        - if: unix
          then: export PETSC_DIR=$PREFIX
          else: set PETSC_DIR=%LIBRARY_PREFIX%
        - cd src/binding/petsc4py
        - ${{ PYTHON }} conf/cythonize.py
        - ${{ PYTHON }} -m pip install . --no-deps -vv
    requirements:
      build:
        - ${{ compiler('c') }}
        - if: build_platform != target_platform
          then:
            - python
            - cython
            - cross-python_${{ target_platform }}
            - numpy
            - if: mpi == 'openmpi'
              then: ${{ mpi }}
      host:
        - python
        - cython
        - pip
        - setuptools
        - numpy >=2.0.0
        - ${{ mpi }}
        - ${{ pin_subpackage('petsc', upper_bound='x.x') }}
      run:
        - python
        - numpy
    tests:
      - python:
          imports:
            - petsc4py
            - petsc4py.PETSc
      - script:
          - python src/binding/petsc4py/test/runtests.py
        files:
          source:
            - src/binding/petsc4py/test

about:
  summary: PETSc with MKL and Intel Pardiso support
  license: BSD-2-Clause
  license_file: LICENSE
  homepage: https://petsc.org/
  repository: https://gitlab.com/petsc/petsc
  documentation: https://petsc.org/release/docs/manual/
