context:
  name: surfa
  version: 0.6.3

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  git: https://github.com/freesurfer/surfa
  rev: "78957160b63a01f4cbfce13b45d63d40d28f87f9"

build:
  number: 0
  script:
    - ${{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython
    - numpy >=2.0.0
  run:
    - scipy
    - numpy >=1.26.4
    - nibabel >= 2.1
    - pillow
    - python-xxhash

tests:
  - python:
      imports:
        - surfa
  - script:
      - pytest -s test
    files:
      source:
        - test/
    requirements:
      run:
        - pytest

about:
  homepage: https://github.com/freesurfer/surfa
  license: MIT
  summary: Python utilities for medical image and surface-based analysis
  repository: https://github.com/freesurfer/surfa
  documentation: https://surfer.nmr.mgh.harvard.edu/docs/surfa/
