context:
  name: cgal-cpp
  version: 5.6.3

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/CGAL/cgal/releases/download/v${{ version }}/CGAL-${{ version }}.tar.xz

build:
  number: 0
  script:
    - if: unix
      then: |
        mkdir build && cd build
        cmake ${CMAKE_ARGS} -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DCGAL_INSTALL_LIB_DIR=lib \
          -DWITH_CGAL_ImageIO=OFF \
          -DWITH_CGAL_Qt5=OFF \
          ..
        cmake --build . --target install
      else: |
        mkdir build && cd build
        cmake %CMAKE_ARGS% -G Ninja ^
          -DCMAKE_BUILD_TYPE=Release ^
          -DWITH_CGAL_ImageIO=OFF ^
          -DWITH_CGAL_Qt5=OFF ^
          -DBoost_USE_STATIC_LIBS=OFF ^
          ..
        cmake --build . --target install

requirements:
  build:
    - ${{ compiler('c') }} 
    - ${{ compiler('cxx') }} 
    - cmake
    - ninja
  host:
    - libboost-devel
    - mpfr
    - eigen
    - eigen-abi-devel
  run:
    - libboost-devel
    - mpfr
    - eigen

about:
  homepage: http://www.cgal.org/
  license: GPL-3.0-only
  summary: Computational Geometry Algorithms Library
  repository: https://github.com/CGAL/cgal
  documentation: https://www.cgal.org/documentation.html
