context:
  name: cgal-cpp
  version: 5.6.3

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/CGAL/cgal/releases/download/v${{ version }}/CGAL-${{ version }}.tar.xz

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }} 
    - ${{ compiler('cxx') }} 
    - cmake
    - ninja
  host:
    - libboost-devel
    - mpfr
    - eigen
    - eigen-abi-devel
  run:
    - libboost-devel
    - mpfr
    - eigen

about:
  homepage: http://www.cgal.org/
  license: GPL-3.0-only
  summary: Computational Geometry Algorithms Library
  repository: https://github.com/CGAL/cgal
  documentation: https://www.cgal.org/documentation.html
