context:
  name: fmm3dpy
  version: 2.1.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  git: https://github.com/vcubiomag/FMM3D.git
  rev: "314cff1a99966a568fb71a1f4ba4124a741cfc4e"

build:
  number: 0
  script:
    - ${{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('fortran') }}
  host:
    - python
    - pip
    - meson-python
    - numpy >=2.0.0
  run:
    - python
    - numpy

tests:
  - python:
      imports:
        - fmm3dpy
  - script:
      - pytest -s python/test
    files:
      source:
        - python/test/
    requirements:
      run:
        - pytest

about:
  homepage: https://github.com/flatironinstitute/FMM3D
  license: Apache-2.0
  summary: This package contains basic routines for Laplace, Helmholtz, Stokes and Maxwell fast multipole methods in three dimensions
  repository: https://github.com/flatironinstitute/FMM3D
  documentation: https://fmm3d.readthedocs.io/en/latest/
