schema_version: 1

context:
  version: "3.1.0"

package:
  name: hypre
  version: ${{ version }}

source:
  url: https://github.com/hypre-space/hypre/archive/v${{ version }}.tar.gz
  sha256: a6879ae9375d95c26afd97141d61e7a8092807333bf40cd180b385aed7351b2d

build:
  number: 0
  skip: unix

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - msmpi
    - libblas
    - liblapack
  run_exports:
    weak:
      - ${{ pin_subpackage('hypre', upper_bound='x.x') }}

tests:
  - package_contents:
      lib:
        - HYPRE
      include:
        - HYPRE.h

about:
  summary: High performance preconditioners for sparse linear systems (Windows build)
  license: Apache-2.0
  license_file: COPYRIGHT
  homepage: https://github.com/hypre-space/hypre
  repository: https://github.com/hypre-space/hypre
