schema_version: 1

context:
  version: "4.6.0"

package:
  name: simnibs
  version: ${{ version }}

source:
  git: https://github.com/vcubiomag/simnibs.git
  rev: "06a9d565cfdeecaf5120518bc4db494d79ef6afd"

build:
  skip: win or match(python, "<3.11")
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
  host:
    - python
    - pip
    - scikit-build-core
    - numpy >=2.0.0
    - cython
    - cgal-cpp >=6,<7
    - tbb-devel
    - eigen
  run:
    - python
    - numpy
    - cgal-cpp
    - tbb-devel
    - eigen
    - scipy
    - h5py
    - nibabel
    - cortech
    - python-mumps
    - petsc4py
    - mpich
    - if: linux or win
      then: petsc * mkl_real_*
    - jsonschema
    - fmm3dpy
    - pygpc
    - samseg
    - pytorch
    - brainnet
    - numba
    - requests
    - gmsh

tests:
  - python:
      imports:
        - simnibs
  - script:
      - pytest -v tests
    files:
      source:
        - tests/
    requirements:
      run:
        - pytest
        - mock
