context:
  name: brainsynth
  version: 0.1

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  git: https://github.com/simnibs/brainsynth
  rev: "daaa07b7c3f83fa7b0a5563ec5c1fc6ed78a3b72"

build:
  noarch: python 
  script: ${{ PYTHON }} -m pip install . -v --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - pytorch
    - nibabel
    - scipy
    - numpy

tests:
  - python:
      imports:
        - brainsynth
