name: Build and Upload Conda Package

permissions:
  id-token: write

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target-platform: linux-64
          - os: windows-latest
            target-platform: win-64
          - os: macos-15
            target-platform: osx-arm64
          - os: macos-15-intel
            target-platform: osx-64
      fail-fast: false

    name: Build (${{ matrix.target-platform }})
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Setup VisualStudio BuildTools
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $installer = "C:\Program Files (x86)\Microsoft Visual Studio\Installer\setup.exe"
          Start-Process -FilePath $installer -Wait -ArgumentList `
            "modify", `
            "--installPath", "C:\Program Files\Microsoft Visual Studio\2022\Enterprise", `
            "--add", "Microsoft.VisualStudio.Component.VC.v141.x86.x64", `
            "--quiet", "--norestart"

      - name: Setup rattler-build
        uses: prefix-dev/rattler-build-action@v0.2.36
        with:
          setup-only: true
      
      - name: Build packages
        shell: bash
        run: |
          rattler-build build --recipe surfa --recipe samseg --recipe pygpc --recipe petsc --recipe fmm3dpy --recipe cgal-cpp \
            --skip-existing=all --experimental \
            -c conda-forge -c https://prefix.dev/vcubiomag

      - name: Upload packages
        run: |
          for pkg in $(find output -type f \( -name "*.conda" -o -name "*.tar.bz2" \) ); do
            echo "Uploading ${pkg}"
            rattler-build upload prefix -c vcubiomag "${pkg}"
          done
